{
 "title": "emqttb",
 "time": { "from": "2022-06-12T15:50:58.789Z", "to": "2022-06-12T15:53:15.247Z" },
 "panels": [
  {
   "title": "Number of workers per group",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "group_n_workers{}", "legendFormat": "{{group}}" }
   ]
  },
  {
   "title": "Client spawn rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rate(group_n_workers{}[2s])", "legendFormat": "{{group}}" }
   ]
  },
  {
   "title": "Published messages per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(emqttb_published_messages{}[2s])",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Received messages per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(emqttb_received_messages{}[2s])",
     "legendFormat": "{{group}}"
    }
   ]
  }
 ]
}