#+TITLE: EMQTT bench daemon
* Concepts
- Worker: a process that corresponds to a single mqtt clients
- Behavior: a function executed by the worker. For example the client can subscribe or publish to topics, or connect and disconnect at certain intervals
- Group: a group of workers with the same behavior
- Scenario: a script that creates several worker groups and controls the number of clients in each group.
  This application can only execute one scenario at a time.
- Stage: scenario can be split into stages, e.g. first connect clients, then start traffic.
  Clients can also disconnect
- Autorate: a function that derives the maximum allowed rate of ramping-up/down the group (e.g. based on the available RAM or CPU or constant parameters)

* Clustering
EMQTTB nodes can operate as a cluster or as group of standalone nodes.

When used in cluster mode, the API commands are broadcast to all nodes.

* Design rules

Save memory by

- Avoiding to store state in the workers, the only thing that worker process stores in its state is worker ID
- Worker state is calculated based on the worker ID, and the persistent terms indexed by the worker's group leader
- Avoid ETS (they cause copying of the terms to the workers' heap)
