:!sectids:
= Documentation

[id=scenarios.emqttb_scenario_pubsub_forward]
== run scenario pubsub_forward

First all subscribers connect and subscribe to the brokers, then the
publishers start to connect and publish.  The default is to use full
forwarding of messages between the nodes: that is, each publisher
client publishes to a topic subscribed by a single client, and both
clients reside on distinct nodes.

Full forwarding of messages is the default and can be set by full_forwarding.

=== Examples
==== Basic usage

[code,bash]
----
./emqttb --restapi @pubsub_fwd --publatency 10ms --num-clients 400 -i 70ms \
                   @g -h 172.25.0.2:1883,172.25.0.3:1883,172.25.0.4:1883
----

In this example the loadgen connects to a list of brokers
in a round-robin in the declared order.  First all the
subscribers, then the publishers, with the difference that
publishers will shift the given host list by one position
to ensure each publisher and subscriber pair will reside
on different hosts, thus forcing all messages to be
forwarded.

[id=autorate]
== Autorate configuration

When the loadgen creates too much traffic, the system may get overloaded.
In this case, the test usually has to be restarted all over again with different parameters.
This can be very expensive in man-hours and computing resources.

In order to prevent that, emqttb can tune some parameters (such as message publishing interval)
automatically using https://controlguru.com/integral-reset-windup-jacketing-logic-and-the-velocity-pi-form/[PI controller].

[id=interval]
== Default interval between events

Supported units:

* `us`: microseconds
* `ms`: milliseconds
* `s`: seconds
* `min`: minutes
* `h` : hours

If unit is not specified then `ms` is assumed.

[id=autorate._.id]
== ID of the autorate configuration

Autorate configuration can be referred by id.

[id=scenarios.emqttb_scenario_pub]
== Run scenario pub

This scenario starts `-N` workers, which publish messages to the specified topic at period `--pubinterval`.
The only mandatory parameter is `--topic`, which supports pattern substitutions.

=== Examples
==== Basic usage

[code,bash]
----
emqttb @pub -t foo/%n -N 100 -i 10ms -s 1kb
----

In this example the loadgen connects to the default broker <link xlink:href="mqtt://localhost:1883"/>,
starts 100 publishers which send messages to topic with the suffix of the worker id every 10 milliseconds. Size of the messages is 1kb.

==== Changing client settings

[code,bash]
----
emqttb @pub -t foo/%n @g --ssl --transport ws -h 127.0.0.1
----

In this example settings of the default client group has been changed: TLS encryption is enabled, and WebSocket transport is used.
Also the hostname of the broker is specified explicitly.

[code,bash]
----
emqttb @pub -t foo/%n -q 1 -g pub @g -g pub --ssl --transport ws -h 127.0.0.1
----

The below example is similar to the previous one, except QoS of the messages is set to 1,
and a dedicated client configuration with id `pub` is used for the publishers.
It's useful for running multiple scenarios (e.g. `@pub` and `@sub`) in parallel, when they must use
different settings. For example, it can be used for testing MQTT bridge.


==== Tuning publishing rate automatically

By default, `@pub` scenario keeps `pubinterval` constant.
However, in some situations it should be tuned dynamically: suppose one wants to measure what publishing rate the broker can sustain while keeping publish latency under `--publatency`.

This is also useful for preventing system overload.
Generating too much load can bring the system down, and the test has to be started all over again with different parameters.
Sometimes finding the correct rate takes many attempts, wasting human and machine time.
Dynamic tuning of the publishing rate for keeping the latency constant can help in this situation.

By default the maximum speed of rate adjustment is set to 0, effectively locking the `pubinterval` at a constant value.
To enable automatic tuning, the autorate speed `-V` must be set to a non-zero value, also it makes sense to set
the minimum (`-m`) and maximum (`-M`) values of the autorate:

[code,bash]
----
emqttb @pub -t foo -i 1s -q 1 --publatency 50ms @a -V 10 -m 0 -M 10000
----

Once automatic adjustment of the publishing interval is enabled, `-i` parameter sets the starting value of the publish interval,
rather than the constant value. So the above example reads like this:

Publish messages to topic `foo` with QoS 1, starting at the publishing interval of 1000 milliseconds, dynamically adjusting it
so to keep the publishing latency around 50 milliseconds. The publishing interval is kept between 0 and 10 seconds,
and the maximum rate of its change is 10 milliseconds per second.

[id=scenarios.emqttb_scenario_pub._.topic]
== Topic where the clients shall publish messages

Topic is a mandatory parameter. It supports the following substitutions:

* `%n` is replaced with the worker ID (integer)
* `%g` is replaced with the group ID
* `%h` is replaced with the hostname

[id=scenarios.emqttb_scenario_persistent_session._.pub.qos]
== QoS of the published messages

Warning: changing QoS to any value other then 2 is likely to cause consume stage to hang,
since it has to consume the exact number of messages as previously produced.

[id=scenarios.emqttb_scenario_persistent_session._.sub.qos]
== Subscription QoS

Warning: changing QoS to any value other then 2 is likely to cause consume stage to hang,
since it has to consume the exact number of messages as previously produced.


[id=groups._.client.clientid]
== Clientid pattern

Pattern used to generate ClientID.
The following substitutions are supported:

* `%n` is replaced with the worker ID (integer)
* `%g` is replaced with the group ID
* `%h` is replaced with the hostname

[id=autorate._.update_interval]
== How often autorate is updated

This parameter governs how often error is calculated and control parameter is updated.

[id=autorate._.speed]
== Maximum rate of change of the controlled parameter

Note: this parameter can be set to 0 to effectively disable autorate and lock control parameter in place.
