name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp:
          - "26.2.3-1"
        os:
          - ubuntu24.04
    container:
      image: ghcr.io/emqx/emqx-builder/5.3-6:1.15.7-${{ matrix.otp }}-${{ matrix.os }}

    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      with:
        fetch-depth: 0
    - name: Install additional packages
      run: |
        apt-get update
        apt-get install -y openjdk-11-jdk asciidoctor xsltproc docbook-xsl
    - name: Compile and run tests
      env:
        BUILD_WITHOUT_QUIC: "true"
      run: |
        git config --global --add safe.directory $(pwd)
        make all docs
    - name: Create release package
      shell: bash
      run: |
        make release
    - if: failure()
      run: cat rebar3.crashdump
    - run: ./_build/default/bin/emqttb
    - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
      with:
        name: packages
        path: ./*.tar.gz
